basePath: /api
definitions:
  service.Domain:
    properties:
      ali_domain:
        type: boolean
      domain_id:
        type: string
      domain_name:
        type: string
      puny_code:
        type: string
    type: object
  service.DomainRecord:
    properties:
      line:
        type: string
      locked:
        type: boolean
      priority:
        type: integer
      record_id:
        type: string
      rr:
        type: string
      status:
        type: string
      ttl:
        type: integer
      type:
        type: string
      value:
        type: string
    type: object
info:
  contact: { }
  description: 阿里云DNS管理服务API
  title: DNS Update API
  version: "1.0"
paths:
  /domains:
    get:
      consumes:
        - application/json
      description: 获取账户下所有的域名列表
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.Domain'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 获取域名列表
      tags:
        - domain-management
  /domains/{domain}/records:
    get:
      consumes:
        - application/json
      description: 获取指定域名的所有解析记录
      parameters:
        - description: 域名
          in: path
          name: domain
          required: true
          type: string
        - description: 每页记录数，默认20
          in: query
          maximum: 500
          minimum: 1
          name: page_size
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.DomainRecord'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 获取域名解析记录
      tags:
        - record-management
  /domains/{domain}/records/id/{record_id}:
    get:
      consumes:
        - application/json
      description: 根据记录ID查询单个域名解析记录
      parameters:
        - description: 域名
          in: path
          name: domain
          required: true
          type: string
        - description: 解析记录ID
          in: path
          name: record_id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.DomainRecord'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 按记录ID查询解析记录
      tags:
        - record-query
  /domains/{domain}/records/rr/{rr}:
    get:
      consumes:
        - application/json
      description: 根据主机记录查询域名解析记录
      parameters:
        - description: 域名
          in: path
          name: domain
          required: true
          type: string
        - description: 主机记录
          in: path
          name: rr
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.DomainRecord'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 按主机记录查询解析记录
      tags:
        - record-query
  /domains/{domain}/records/search:
    get:
      consumes:
        - application/json
      description: 根据多个条件搜索域名解析记录
      parameters:
        - description: 域名
          in: path
          name: domain
          required: true
          type: string
        - description: 解析记录ID
          in: query
          name: record_id
          type: string
        - description: 主机记录
          in: query
          name: rr
          type: string
        - description: 记录类型
          in: query
          name: type
          type: string
        - description: 状态(Enable/Disable)
          in: query
          name: status
          type: string
        - description: 每页记录数，默认20
          in: query
          maximum: 500
          minimum: 1
          name: page_size
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.DomainRecord'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 搜索域名解析记录
      tags:
        - record-query
  /domains/{domain}/records/status/{status}:
    get:
      consumes:
        - application/json
      description: 查询指定域名下所有特定状态的解析记录
      parameters:
        - description: 域名
          in: path
          name: domain
          required: true
          type: string
        - description: 状态(Enable/Disable)
          in: path
          name: status
          required: true
          type: string
        - description: 每页记录数，默认20
          in: query
          maximum: 500
          minimum: 1
          name: page_size
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.DomainRecord'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 按记录状态查询解析记录
      tags:
        - record-query
  /domains/{domain}/records/type/{type}:
    get:
      consumes:
        - application/json
      description: 根据记录类型查询域名解析记录
      parameters:
        - description: 域名
          in: path
          name: domain
          required: true
          type: string
        - description: 记录类型
          in: path
          name: type
          required: true
          type: string
        - description: 每页记录数，默认20
          in: query
          maximum: 500
          minimum: 1
          name: page_size
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.DomainRecord'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 按记录类型查询解析记录
      tags:
        - record-query
swagger: "2.0"
